M48
; DRILL file {KiCad 7.0.10} date Monday, April 07, 2025 at 09:25:58 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-07T09:25:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.150
%
G90
G05
T1
X100.58Y-66.39
X100.61Y-69.08
X103.37Y-70.21
X103.44Y-65.32
M30
